CREATE TABLE `t_user` (
	`c_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '联系人ID',
	`c_account` VARCHAR(50) NOT NULL COMMENT '账号' COLLATE 'utf8mb4_bin',
	`c_nickname` VARCHAR(50) NULL DEFAULT NULL COMMENT '昵称' COLLATE 'utf8mb4_bin',
	`c_password` VARCHAR(128) NULL DEFAULT NULL COMMENT '密码' COLLATE 'utf8mb4_bin',
	`c_avatar` VARCHAR(255) NULL DEFAULT NULL COMMENT '头像URL' COLLATE 'utf8mb4_bin',
	`c_created_user_id` INT(10) UNSIGNED NOT NULL COMMENT '创建者ID',
	`c_updated_user_id` INT(10) UNSIGNED NOT NULL COMMENT '更新者ID',
	`c_created_time` TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP) COMMENT '创建时间',
	`c_updated_time` TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (`c_id`) USING BTREE
)
COMMENT='联系人信息表'
COLLATE='utf8mb4_bin'
ENGINE=InnoDB
AUTO_INCREMENT=9
;
CREATE TABLE `t_user_friend` (
	`c_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '关联ID',
	`c_user_id` INT(10) UNSIGNED NOT NULL COMMENT '联系人ID',
	`c_friend_id` INT(10) UNSIGNED NOT NULL COMMENT '好友ID',
	`c_display` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT '是否显示 1:显示 0:不显示',
	`c_created_user_id` INT(10) UNSIGNED NOT NULL COMMENT '创建者ID',
	`c_updated_user_id` INT(10) UNSIGNED NOT NULL COMMENT '更新者ID',
	`c_created_time` TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP) COMMENT '创建时间',
	`c_updated_time` TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (`c_id`) USING BTREE
)
COMMENT='联系人-好友关联表'
COLLATE='utf8mb4_bin'
ENGINE=InnoDB
AUTO_INCREMENT=7
;
CREATE TABLE `t_group` (
	`c_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '群组ID',
	`c_name` VARCHAR(100) NOT NULL COMMENT '群组名称' COLLATE 'utf8mb4_bin',
	`c_avatar` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	`c_description` VARCHAR(255) NULL DEFAULT NULL COMMENT '群组描述' COLLATE 'utf8mb4_bin',
	`c_created_user_id` INT(10) UNSIGNED NOT NULL COMMENT '创建者ID',
	`c_updated_user_id` INT(10) UNSIGNED NOT NULL COMMENT '更新者ID',
	`c_created_time` TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP) COMMENT '创建时间',
	`c_updated_time` TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (`c_id`) USING BTREE
)
COMMENT='群组信息表'
COLLATE='utf8mb4_bin'
ENGINE=InnoDB
AUTO_INCREMENT=4
;
CREATE TABLE `t_user_group` (
	`c_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '关联ID',
	`c_user_id` INT(10) UNSIGNED NOT NULL COMMENT '联系人ID',
	`c_group_id` INT(10) UNSIGNED NOT NULL COMMENT '群组ID',
	`c_created_user_id` INT(10) UNSIGNED NOT NULL COMMENT '创建者ID',
	`c_updated_user_id` INT(10) UNSIGNED NOT NULL COMMENT '更新者ID',
	`c_created_time` TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP) COMMENT '创建时间',
	`c_updated_time` TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (`c_id`) USING BTREE
)
COMMENT='联系人-群组关联表'
COLLATE='utf8mb4_bin'
ENGINE=InnoDB
AUTO_INCREMENT=6
;
